// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plhsjyqfwclnmuprkjjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsaHNqeXFmd2Nsbm11cHJramp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2Nzk3ODEsImV4cCI6MjA2NjI1NTc4MX0.NaUAkkw0l_n9WhXhnz3z92BK-735c8SvziDUASQZoJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);